config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'pages/home', to: 'pages#home'

  resources :buildings do
    resources :sensors do
      resources :measurements, except: [:create]
    end
  end

  post 'measurements', to: 'measurements#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  has_many :sensors, dependent: :destroy
end

app/models/measurement.rb
class Measurement < ApplicationRecord
  belongs_to :sensor
end

app/models/sensor.rb
class Sensor < ApplicationRecord
  belongs_to :building
  has_many :measurements, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

  skip_before_action :verify_authenticity_token

    def show
      @building = Building.find(params[:id])
    end

    def create
      @body = building_params['building']
      @body.each do |b|
        Building.create!(b)
      end
    end

    private

      def building_params
        params.require(:buildings).permit(building: [:id, :description, :construction_year,
              :location, :location_x, :location_y, :flats, :floors,
              :cellar, :bim, :roof_area, :blind_facade_area, :opend_facade_area,
              :gross_surface_area, :total_pra, :process_pra, :product_pra])
      end

end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @measurements = Sensor.find(params[:sensor_id]).measurements
  end

  def create
    @body = building_params['measurement']
    @body.each do |m|
      Measurement.create!(m)
    end
  end

  private

    def building_params
      params.require(:data).permit(measurement: [:sensor_id, :value,
         :units, :timestamp])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @sensors = Building.find(params[:building_id]).sensors
  end

  def create
    @body = building_params['sensor']
    @body.each do |s|
      Sensor.create!(s)
    end
  end

  private

    def building_params
      params.require(:sensors).permit(sensor: [:id, :building_id, :category])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buildings/show.html.erb
<div>
  <div class="card text-center">
    <h1><%= @building.location %> (<%= @building.location_x %>, <%= @building.location_y %>)</h1>
    <div class="card-body">
      <h5 class="card-title"><%= @building.description %></h5>
      <p class="card-text">Constructed on <%= @building.construction_year %></p>
      <%= link_to "Available Sensors", building_sensors_path(@building), class: "btn btn-primary" %>
      <a href="#" class="btn btn-primary">Energy Data</a>
      <a href="#" class="btn btn-primary">Upgrades History</a>
    </div>
  </div>
  <div class="d-flex justify-content-center">
  <h2>Building Info</h2>
  </div>
  <div class="d-flex justify-content-center">
      <table class="table center" style="width: 50%">
        <thead>
          <tr>
            <th scope="col">Column Name</th>
            <th scope="col">Value</th>
          </tr>
        </thead>
        <tbody>
          <% Building.column_names.each do |col| %>
            <tr>
              <td> <%= col %> </td>
              <td class="text-right"> <%= @building[col] %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">RINNO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Pilots
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% Building.all.each do |b| %>
            <%= link_to "Pilot #{b.id}", b, class: "dropdown-item" %>
          <% end %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RinnoDataPlatform</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/measurements/index.html.erb
<div class="">
  <table class="table table-striped text-center">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Value</th>
        <th scope="col">Units</th>
      </tr>
    </thead>
    <tbody>
      <% @measurements.each do |s| %>
        <tr>
          <td><%= s.id %></td>
          <td><%= s.value %></td>
          <td><%= s.units %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/measurements/test.html.erb
<%= @body %>

app/views/pages/home.html.erb
<div>
  Home Page
</div>

app/views/sensors/index.html.erb
<div class="">
  <table class="table table-striped text-center">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Type</th>
        <th scope="col">Measurements</th>
      </tr>
    </thead>
    <tbody>
      <% @sensors.each do |s| %>
        <tr>
          <td><%= s.id %></td>
          <td><%= s.category %></td>
          <td><%= link_to "View", building_sensor_measurements_path(s.building, s) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>